# Generated by Django 4.0.6 on 2022-09-28 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import misc_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=75)),
                ('tldr', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to=misc_utils.upload_image)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_editted', models.DateTimeField(auto_now=True)),
                ('edited', models.BooleanField(default=False)),
                ('post_ID', models.CharField(default=misc_utils.id_generator, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='static_user_id')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('content', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('edited', models.BooleanField(default=False)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('comment_ID', models.CharField(default=misc_utils.id_generator, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('post_commented_on', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Engagements.post')),
            ],
        ),
    ]
